name: Make Images owo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build Artifact
        run: ./gradlew nativeCompile
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ask-${{ matrix.os }}
          path: build/native/nativeCompile/*
